# Generated by Django 4.2.11 on 2024-04-05 04:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_alter_room_options_alter_room_status'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='room',
            options={'ordering': ('-created_at', '-status')},
        ),
        migrations.AlterField(
            model_name='room',
            name='status',
            field=models.CharField(choices=[('closed', 'Closed'), ('active', 'Active'), ('waiting', 'Waiting')], default='waiting', max_length=20),
        ),
    ]
